--deleting all rows
DELETE FROM ORGANIZATION; 
DELETE FROM HOTEL;
DELETE FROM CONFERENCE;
DELETE FROM ATTENDEE;

--deleting all tables
DROP TABLE ORGANIZATION CASCADE;
DROP TABLE HOTEL CASCADE;
DROP TABLE CONFERENCE CASCADE;
DROP TABLE ATTENDEE CASCADE;
